title: Simulating Strategic Interactions with AI Agents
description: Expanding Management Theory Through AI-Powered Simulations
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
baseurl: /theorizing_with_llms/
code_url: /theorizing_with_llms/code.html
paper_url: https://www.abhishekn.com/s/GABE_Streetlight_Effect_Sep24.pdf
contact_url: https://www.abhishekn.com/about-lab